In [1]:
import pandas as pd

In [2]:
data = pd.read_excel('datos_municipales_20211015002650_Sin-Corrección-Monetaria.xlsx')
data

,Valores en miles de pesos nominales (M$) de cada año.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,RSHNH40 (N°) Número de Hogares de 0-40% de Ing...,RSHNH50 (N°) Número de Hogares de 41-50% de In...,RSHNH60 (N°) Número de Hogares de 51-60 % de I...,RSHNH70 (N°) Número de Hogares de 61-70% de In...,RSHNH80 (N°) Número de Hogares de 71-80% de In...,RSHNH90 (N°) Número de Hogares de 81-90% de In...,RSHNH100 (N°) Número de Hogares de 91-100% de ...,RSHPORH40 (%) Porcentaje de Hogares de 0-40% d...,RSHPORH50 (%) Porcentaje de Hogares de 41-50% ...,RSHPORH60 (%) Porcentaje de Hogares de 51-60% ...,RSHPORH70 (%) Porcentaje de Hogares de 61-70% ...,RSHPORH80 (%) Porcentaje de Hogares de 71-80% ...,RSHPORH90 (%) Porcentaje de Hogares de 81-90% ...,RSHPORH100 (%) Porcentaje de Hogares de 91-100...
1,CODIGO,MUNICIPIO,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020
2,1101,IQUIQUE,33695,5391,4629,4462,5019,7271,4298,50,54,55,56,57,58,59
3,1107,ALTO HOSPICIO,26549,3720,3030,2792,3007,4204,2309,40,37,36,35,34,34,32
4,1401,POZO ALMONTE,3308,498,412,404,438,609,409,5,5,5,5,5,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,16301,SAN CARLOS,14461,1525,1216,1123,1110,1197,675,11,10,10,11,11,10,11
343,16302,COIHUECO,7761,699,506,471,410,402,167,6,5,4,5,4,3,3
344,16303,ÑIQUÉN,3760,360,256,195,139,193,91,3,2,2,2,1,2,1
345,16304,SAN FABIÁN,1835,141,99,117,111,108,75,1,1,1,1,1,1,1
346,16305,SAN NICOLÁS,4112,434,360,250,240,262,114,3,3,3,2,2,2,2

In [3]:
names = []
for a in data.keys():
    names.append(data[a][0])

dict = {}
cont = 0
for a in data.keys():
    if cont == 0 or cont == 1:
        dict[a] = ''
    else:
        dict[a] = names[cont]
    cont += 1

In [4]:
data = data.rename(dict, axis = 'columns')
data.head()

,,,RSHNH40 (N°) Número de Hogares de 0-40% de Ingresos (RSH),RSHNH50 (N°) Número de Hogares de 41-50% de Ingresos (RSH),RSHNH60 (N°) Número de Hogares de 51-60 % de Ingresos (RSH),RSHNH70 (N°) Número de Hogares de 61-70% de Ingresos (RSH),RSHNH80 (N°) Número de Hogares de 71-80% de Ingresos (RSH),RSHNH90 (N°) Número de Hogares de 81-90% de Ingresos (RSH),RSHNH100 (N°) Número de Hogares de 91-100% de Ingresos (RSH),RSHPORH40 (%) Porcentaje de Hogares de 0-40% de Ingresos respecto del Total Regional (RSH),RSHPORH50 (%) Porcentaje de Hogares de 41-50% de Ingresos respecto del Total Regional (RSH),RSHPORH60 (%) Porcentaje de Hogares de 51-60% de Ingresos respecto del Total Regional (RSH),RSHPORH70 (%) Porcentaje de Hogares de 61-70% de Ingresos respecto del Total Regional (RSH),RSHPORH80 (%) Porcentaje de Hogares de 71-80% de Ingresos respecto del Total Regional (RSH),RSHPORH90 (%) Porcentaje de Hogares de 81-90% de Ingresos respecto del Total Regional (RSH),RSHPORH100 (%) Porcentaje de Hogares de 91-100% de Ingresos respecto del Total Regional (RSH)
0,NaN,NaN,RSHNH40 (N°) Número de Hogares de 0-40% de Ing...,RSHNH50 (N°) Número de Hogares de 41-50% de In...,RSHNH60 (N°) Número de Hogares de 51-60 % de I...,RSHNH70 (N°) Número de Hogares de 61-70% de In...,RSHNH80 (N°) Número de Hogares de 71-80% de In...,RSHNH90 (N°) Número de Hogares de 81-90% de In...,RSHNH100 (N°) Número de Hogares de 91-100% de ...,RSHPORH40 (%) Porcentaje de Hogares de 0-40% d...,RSHPORH50 (%) Porcentaje de Hogares de 41-50% ...,RSHPORH60 (%) Porcentaje de Hogares de 51-60% ...,RSHPORH70 (%) Porcentaje de Hogares de 61-70% ...,RSHPORH80 (%) Porcentaje de Hogares de 71-80% ...,RSHPORH90 (%) Porcentaje de Hogares de 81-90% ...,RSHPORH100 (%) Porcentaje de Hogares de 91-100...
1,CODIGO,MUNICIPIO,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020
2,1101,IQUIQUE,33695,5391,4629,4462,5019,7271,4298,50,54,55,56,57,58,59
3,1107,ALTO HOSPICIO,26549,3720,3030,2792,3007,4204,2309,40,37,36,35,34,34,32
4,1401,POZO ALMONTE,3308,498,412,404,438,609,409,5,5,5,5,5,5,6

In [5]:
data = data.drop(0, axis = 'rows')
data

,,,RSHNH40 (N°) Número de Hogares de 0-40% de Ingresos (RSH),RSHNH50 (N°) Número de Hogares de 41-50% de Ingresos (RSH),RSHNH60 (N°) Número de Hogares de 51-60 % de Ingresos (RSH),RSHNH70 (N°) Número de Hogares de 61-70% de Ingresos (RSH),RSHNH80 (N°) Número de Hogares de 71-80% de Ingresos (RSH),RSHNH90 (N°) Número de Hogares de 81-90% de Ingresos (RSH),RSHNH100 (N°) Número de Hogares de 91-100% de Ingresos (RSH),RSHPORH40 (%) Porcentaje de Hogares de 0-40% de Ingresos respecto del Total Regional (RSH),RSHPORH50 (%) Porcentaje de Hogares de 41-50% de Ingresos respecto del Total Regional (RSH),RSHPORH60 (%) Porcentaje de Hogares de 51-60% de Ingresos respecto del Total Regional (RSH),RSHPORH70 (%) Porcentaje de Hogares de 61-70% de Ingresos respecto del Total Regional (RSH),RSHPORH80 (%) Porcentaje de Hogares de 71-80% de Ingresos respecto del Total Regional (RSH),RSHPORH90 (%) Porcentaje de Hogares de 81-90% de Ingresos respecto del Total Regional (RSH),RSHPORH100 (%) Porcentaje de Hogares de 91-100% de Ingresos respecto del Total Regional (RSH)
1,CODIGO,MUNICIPIO,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020
2,1101,IQUIQUE,33695,5391,4629,4462,5019,7271,4298,50,54,55,56,57,58,59
3,1107,ALTO HOSPICIO,26549,3720,3030,2792,3007,4204,2309,40,37,36,35,34,34,32
4,1401,POZO ALMONTE,3308,498,412,404,438,609,409,5,5,5,5,5,5,6
5,1402,CAMIÑA,451,38,23,18,18,26,13,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,16301,SAN CARLOS,14461,1525,1216,1123,1110,1197,675,11,10,10,11,11,10,11
343,16302,COIHUECO,7761,699,506,471,410,402,167,6,5,4,5,4,3,3
344,16303,ÑIQUÉN,3760,360,256,195,139,193,91,3,2,2,2,1,2,1
345,16304,SAN FABIÁN,1835,141,99,117,111,108,75,1,1,1,1,1,1,1
346,16305,SAN NICOLÁS,4112,434,360,250,240,262,114,3,3,3,2,2,2,2

In [6]:
# No hay datos nulos
cont = 0
for a in data.keys():
    for item in data[a].isna():
        if item == True:
            cont+=1
cont

0

In [7]:
# No hay datos duplicados
cont = 0
for item in data.duplicated():
    if item == True:
        cont += 1
cont

0

# Influencia del ingreso económico en el rendimiento en enseñanza media.

In [8]:
excel = pd.read_excel('Ingreso_Casen_en_Pandemia_2020.xlsx', '4')
excel[0:10]

,Indice,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ingreso promedio de los hogares por tipo de in...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ingreso promedio de los hogares por tipo de in...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2006-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2006-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,($ noviembre de cada año),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,($ noviembre de 2020),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,2006.0000,2009.0000,2011.000000,2013.0000,2015.000000,2017.000000,2020.000000,...,NaN,NaN,NaN,2006.000000,2009.000000,2011.000000,2013.000000,2015.000000,2017.000000,2020.000000
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Ingreso del trabajo2,I,Estimación,50156.3830,40113.7150,56169.042125,63696.5440,73046.327352,71980.380233,7023.837107,...,Ingreso del trabajo2,I,Estimación,79949.274502,55918.518710,73469.107099,79684.376544,83199.766854,78170.692933,7023.837107
8,NaN,NaN,Error estándar,1007.8439,1116.1195,2054.145000,1473.9436,1430.449000,1683.905940,348.498057,...,NaN,NaN,Error estándar,1606.503177,1555.870583,2686.821660,1843.903444,1629.281411,1828.721851,348.498057
9,NaN,II,Estimación,128154.1200,143229.2700,159783.860368,191072.9000,224927.592322,235981.996295,114883.663633,...,NaN,II,Estimación,204277.667280,199661.602380,208997.289362,239032.197900,256192.527655,256276.447977,114883.663633

In [9]:
names = []
for a in excel.keys():
    names.append(str(excel[a][5])[0:4])

dicti = {}
cont = 0
for a in excel.keys():
    if cont == 0 or cont == 1:
        dicti[a] = ''
    else:
        dicti[a] = names[cont]
    cont += 1

In [10]:
excel = excel.rename(dicti, axis = 'columns')
excel.head()

,,,nan,2006,2009,2011,2013,2015,2017,2020,...,nan,nan,nan,2006,2009,2011,2013,2015,2017,2020
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ingreso promedio de los hogares por tipo de in...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ingreso promedio de los hogares por tipo de in...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2006-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2006-2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,($ noviembre de cada año),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,($ noviembre de 2020),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
excel.columns.duplicated()

array([False,  True, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [12]:
excel_3 = excel
excel_3 = excel_3.iloc[:,~excel_3.columns.duplicated(keep = 'last')]
excel_3[0:10]

,,nan,2006,2009,2011,2013,2015,2017,2020
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,2006.000000,2009.000000,2011.000000,2013.000000,2015.000000,2017.000000,2020.000000
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,I,Estimación,79949.274502,55918.518710,73469.107099,79684.376544,83199.766854,78170.692933,7023.837107
8,NaN,Error estándar,1606.503177,1555.870583,2686.821660,1843.903444,1629.281411,1828.721851,348.498057
9,II,Estimación,204277.667280,199661.602380,208997.289362,239032.197900,256192.527655,256276.447977,114883.663633

In [13]:
excel_3 = excel_3.drop(excel_3.index[[0, 1, 2, 3, 4, 5, 6]])
excel_3

,,nan,2006,2009,2011,2013,2015,2017,2020
7,I,Estimación,79949.274502,55918.518710,73469.107099,79684.376544,83199.766854,78170.692933,7023.837107
8,NaN,Error estándar,1606.503177,1555.870583,2686.821660,1843.903444,1629.281411,1828.721851,348.498057
9,II,Estimación,204277.667280,199661.602380,208997.289362,239032.197900,256192.527655,256276.447977,114883.663633
10,NaN,Error estándar,2517.561368,2331.976319,3389.071164,3018.534022,2563.661200,2965.963307,2077.063508
11,III,Estimación,282025.128860,268025.495200,289737.667329,322936.154910,347779.108121,349319.547136,244413.607589
...,...,...,...,...,...,...,...,...,...
104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
excel_3[0:91]

,,nan,2006,2009,2011,2013,2015,2017,2020
7,I,Estimación,7.994927e+04,5.591852e+04,7.346911e+04,7.968438e+04,8.319977e+04,7.817069e+04,7.023837e+03
8,NaN,Error estándar,1.606503e+03,1.555871e+03,2.686822e+03,1.843903e+03,1.629281e+03,1.828722e+03,3.484981e+02
9,II,Estimación,2.042777e+05,1.996616e+05,2.089973e+05,2.390322e+05,2.561925e+05,2.562764e+05,1.148837e+05
10,NaN,Error estándar,2.517561e+03,2.331976e+03,3.389071e+03,3.018534e+03,2.563661e+03,2.965963e+03,2.077064e+03
11,III,Estimación,2.820251e+05,2.680255e+05,2.897377e+05,3.229362e+05,3.477791e+05,3.493195e+05,2.444136e+05
...,...,...,...,...,...,...,...,...,...
93,NaN,Error estándar,1.474382e+04,1.707990e+04,1.580611e+04,1.818162e+04,1.378630e+04,1.871624e+04,1.786724e+04
94,X,Estimación,2.806836e+06,2.898267e+06,2.856677e+06,3.258746e+06,3.268921e+06,3.507797e+06,3.433336e+06
95,NaN,Error estándar,6.822379e+04,1.153137e+05,8.145849e+04,7.838663e+04,8.242610e+04,8.919092e+04,7.876168e+04
96,Total,Estimación,7.972399e+05,8.120492e+05,8.207416e+05,9.474132e+05,9.783864e+05,1.028005e+06,9.697787e+05
97,NaN,Error estándar,1.417151e+04,1.644301e+04,1.548188e+04,1.464449e+04,1.226189e+04,1.574543e+04,1.262553e+04

In [15]:
excel_3.head()

,,nan,2006,2009,2011,2013,2015,2017,2020
7,I,Estimación,79949.274502,55918.518710,73469.107099,79684.376544,83199.766854,78170.692933,7023.837107
8,NaN,Error estándar,1606.503177,1555.870583,2686.821660,1843.903444,1629.281411,1828.721851,348.498057
9,II,Estimación,204277.667280,199661.602380,208997.289362,239032.197900,256192.527655,256276.447977,114883.663633
10,NaN,Error estándar,2517.561368,2331.976319,3389.071164,3018.534022,2563.661200,2965.963307,2077.063508
11,III,Estimación,282025.128860,268025.495200,289737.667329,322936.154910,347779.108121,349319.547136,244413.607589

In [ ]:
for item in excel_3.keys():
    for a in excel_3[item]:

In [16]:
cont = 0
for a in excel_3.keys():
    for item in excel_3[a].isna():
        if item == True:
            cont+=1
cont

170

In [38]:
data_final = excel_3.dropna()
data_final

,,nan,2006,2009,2011,2013,2015,2017,2020
7,I,Estimación,7.994927e+04,5.591852e+04,7.346911e+04,7.968438e+04,8.319977e+04,7.817069e+04,7.023837e+03
9,II,Estimación,2.042777e+05,1.996616e+05,2.089973e+05,2.390322e+05,2.561925e+05,2.562764e+05,1.148837e+05
11,III,Estimación,2.820251e+05,2.680255e+05,2.897377e+05,3.229362e+05,3.477791e+05,3.493195e+05,2.444136e+05
13,IV,Estimación,3.556352e+05,3.594968e+05,3.693609e+05,4.068974e+05,4.313956e+05,4.446333e+05,3.188315e+05
15,V,Estimación,4.081656e+05,3.981378e+05,4.271203e+05,4.824036e+05,5.326870e+05,5.311166e+05,4.180603e+05
17,VI,Estimación,4.946633e+05,4.901258e+05,4.919605e+05,5.970943e+05,6.275354e+05,6.684945e+05,5.541271e+05
19,VII,Estimación,6.335337e+05,6.156796e+05,6.134913e+05,7.163107e+05,7.487293e+05,7.777706e+05,6.685613e+05
21,VIII,Estimación,7.787014e+05,7.481028e+05,7.590600e+05,8.710523e+05,9.457709e+05,9.578990e+05,8.812901e+05
23,IX,Estimación,1.082354e+06,1.042140e+06,1.054628e+06,1.271892e+06,1.228070e+06,1.315693e+06,1.349157e+06
25,X,Estimación,2.473316e+06,2.511833e+06,2.503995e+06,2.877024e+06,2.821696e+06,3.052409e+06,2.942239e+06
27,Total,Estimación,6.792330e+05,6.684467e+05,6.792462e+05,7.872924e+05,8.025260e+05,8.438205e+05,7.468647e+05
30,I,Estimación,1.013018e+05,7.418716e+04,9.591873e+04,1.146654e+05,1.197990e+05,1.138554e+05,1.356434e+04
32,II,Estimación,2.467474e+05,2.411136e+05,2.615805e+05,2.973169e+05,3.201258e+05,3.288378e+05,1.973727e+05
34,III,Estimación,3.339612e+05,3.229383e+05,3.462377e+05,4.020803e+05,4.281879e+05,4.382602e+05,3.434616e+05
36,IV,Estimación,4.149938e+05,4.220875e+05,4.392269e+05,4.882522e+05,5.194681e+05,5.339304e+05,4.365600e+05
38,V,Estimación,4.875384e+05,4.758258e+05,5.109367e+05,5.810400e+05,6.308114e+05,6.392014e+05,5.498491e+05
40,VI,Estimación,5.844526e+05,5.816687e+05,5.923642e+05,7.180497e+05,7.437307e+05,7.997165e+05,7.022715e+05
42,VII,Estimación,7.317312e+05,7.204056e+05,7.251670e+05,8.321784e+05,8.840863e+05,9.115796e+05,8.452549e+05
44,VIII,Estimación,9.007689e+05,8.836611e+05,9.034687e+05,1.026592e+06,1.104847e+06,1.120377e+06,1.081747e+06
46,IX,Estimación,1.249369e+06,1.245729e+06,1.252056e+06,1.470697e+06,1.459535e+06,1.546450e+06,1.599886e+06
48,X,Estimación,2.806064e+06,2.896140e+06,2.852938e+06,3.253812e+06,3.264100e+06,3.502355e+06,3.427933e+06
50,Total,Estimación,7.856526e+05,7.858537e+05,7.980860e+05,9.194324e+05,9.477300e+05,9.942157e+05,9.163671e+05
53,I,Estimación,3.768911e+04,7.148138e+04,6.536949e+04,8.056967e+04,8.408309e+04,9.325547e+04,1.109147e+05
55,II,Estimación,1.980512e+04,4.438449e+04,3.912292e+04,4.951819e+04,5.225764e+04,5.790543e+04,1.087803e+05
57,III,Estimación,1.682835e+04,3.749042e+04,3.192698e+04,3.839025e+04,4.274497e+04,4.600054e+04,8.700027e+04
59,IV,Estimación,1.247352e+04,3.051906e+04,2.475919e+04,3.049393e+04,3.310251e+04,3.812136e+04,6.418713e+04
61,V,Estimación,9.723635e+03,2.358028e+04,1.901801e+04,2.484890e+04,2.901878e+04,2.921679e+04,5.074091e+04
63,VI,Estimación,7.127296e+03,1.875650e+04,1.527987e+04,2.055855e+04,2.153977e+04,2.526556e+04,3.947634e+04
65,VII,Estimación,5.635562e+03,1.445960e+04,1.237305e+04,1.472509e+04,1.800437e+04,1.847285e+04,3.226740e+04
67,VIII,Estimación,3.430980e+03,1.135524e+04,9.765914e+03,1.058378e+04,1.264476e+04,1.518696e+04,2.237793e+04
69,IX,Estimación,2.344012e+03,7.218173e+03,5.486521e+03,6.546090e+03,8.496604e+03,9.724300e+03,1.133012e+04
71,X,Estimación,7.719932e+02,2.127703e+03,3.738797e+03,4.933940e+03,4.820922e+03,5.441993e+03,5.403384e+03
73,Total,Estimación,1.158727e+04,2.619552e+04,2.265564e+04,2.798088e+04,3.065646e+04,3.378906e+04,5.341156e+04
76,I,Estimación,1.389909e+05,1.456685e+05,1.612882e+05,1.952351e+05,2.038821e+05,2.071108e+05,1.244791e+05
78,II,Estimación,2.665525e+05,2.854981e+05,3.007034e+05,3.468351e+05,3.723834e+05,3.867432e+05,3.061529e+05
80,III,Estimación,3.507896e+05,3.604287e+05,3.781647e+05,4.404705e+05,4.709329e+05,4.842608e+05,4.304618e+05
82,IV,Estimación,4.274673e+05,4.526066e+05,4.639860e+05,5.187461e+05,5.525706e+05,5.720518e+05,5.007472e+05
84,V,Estimación,4.972620e+05,4.994061e+05,5.299547e+05,6.058889e+05,6.598302e+05,6.684182e+05,6.005900e+05
86,VI,Estimación,5.915799e+05,6.004252e+05,6.076441e+05,7.386083e+05,7.652705e+05,8.249820e+05,7.417479e+05
88,VII,Estimación,7.373667e+05,7.348652e+05,7.375400e+05,8.469035e+05,9.020907e+05,9.300524e+05,8.775223e+05
90,VIII,Estimación,9.041999e+05,8.950163e+05,9.132346e+05,1.037176e+06,1.117492e+06,1.135564e+06,1.104125e+06
92,IX,Estimación,1.251713e+06,1.252947e+06,1.257543e+06,1.477243e+06,1.468032e+06,1.556174e+06,1.611216e+06
94,X,Estimación,2.806836e+06,2.898267e+06,2.856677e+06,3.258746e+06,3.268921e+06,3.507797e+06,3.433336e+06
96,Total,Estimación,7.972399e+05,8.120492e+05,8.207416e+05,9.474132e+05,9.783864e+05,1.028005e+06,9.697787e+05

In [39]:
data_final = data_final.reset_index()
data_final.head()

,index,,nan,2006,2009,2011,2013,2015,2017,2020
0,7,I,Estimación,79949.274502,55918.51871,73469.107099,79684.376544,83199.766854,78170.692933,7023.837107
1,9,II,Estimación,204277.667280,199661.60238,208997.289362,239032.197900,256192.527655,256276.447977,114883.663633
2,11,III,Estimación,282025.128860,268025.49520,289737.667329,322936.154910,347779.108121,349319.547136,244413.607589
3,13,IV,Estimación,355635.235920,359496.80598,369360.867883,406897.445250,431395.620139,444633.327593,318831.540234
4,15,V,Estimación,408165.617500,398137.78898,427120.347053,482403.614400,532686.981101,531116.556329,418060.250257

In [41]:
cont = 0
for item in data_final.keys():
    cont_2 = 0
    for a in data_final[item]:
        if cont>2:
            #print(a)
            data_final[item][cont_2] = round(a)
            cont_2+=1
        
    cont+=1
        
data_final.head()

<ipython-input-41-ae6cdf90fce8>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_final[item][cont_2] = round(a)

,index,,nan,2006,2009,2011,2013,2015,2017,2020
0,7,I,Estimación,79949.0,55919.0,73469.0,79684.0,83200.0,78171.0,7024.0
1,9,II,Estimación,204278.0,199662.0,208997.0,239032.0,256193.0,256276.0,114884.0
2,11,III,Estimación,282025.0,268025.0,289738.0,322936.0,347779.0,349320.0,244414.0
3,13,IV,Estimación,355635.0,359497.0,369361.0,406897.0,431396.0,444633.0,318832.0
4,15,V,Estimación,408166.0,398138.0,427120.0,482404.0,532687.0,531117.0,418060.0

In [22]:
data_final['2006'][7].round()

79949.0

In [42]:
data_final

,index,,nan,2006,2009,2011,2013,2015,2017,2020
0,7,I,Estimación,79949.0,55919.0,73469.0,79684.0,83200.0,78171.0,7024.0
1,9,II,Estimación,204278.0,199662.0,208997.0,239032.0,256193.0,256276.0,114884.0
2,11,III,Estimación,282025.0,268025.0,289738.0,322936.0,347779.0,349320.0,244414.0
3,13,IV,Estimación,355635.0,359497.0,369361.0,406897.0,431396.0,444633.0,318832.0
4,15,V,Estimación,408166.0,398138.0,427120.0,482404.0,532687.0,531117.0,418060.0
5,17,VI,Estimación,494663.0,490126.0,491960.0,597094.0,627535.0,668494.0,554127.0
6,19,VII,Estimación,633534.0,615680.0,613491.0,716311.0,748729.0,777771.0,668561.0
7,21,VIII,Estimación,778701.0,748103.0,759060.0,871052.0,945771.0,957899.0,881290.0
8,23,IX,Estimación,1082354.0,1042140.0,1054628.0,1271892.0,1228070.0,1315693.0,1349157.0
9,25,X,Estimación,2473316.0,2511833.0,2503995.0,2877024.0,2821696.0,3052409.0,2942239.0
10,27,Total,Estimación,679233.0,668447.0,679246.0,787292.0,802526.0,843821.0,746865.0
11,30,I,Estimación,101302.0,74187.0,95919.0,114665.0,119799.0,113855.0,13564.0
12,32,II,Estimación,246747.0,241114.0,261580.0,297317.0,320126.0,328838.0,197373.0
13,34,III,Estimación,333961.0,322938.0,346238.0,402080.0,428188.0,438260.0,343462.0
14,36,IV,Estimación,414994.0,422088.0,439227.0,488252.0,519468.0,533930.0,436560.0
15,38,V,Estimación,487538.0,475826.0,510937.0,581040.0,630811.0,639201.0,549849.0
16,40,VI,Estimación,584453.0,581669.0,592364.0,718050.0,743731.0,799716.0,702272.0
17,42,VII,Estimación,731731.0,720406.0,725167.0,832178.0,884086.0,911580.0,845255.0
18,44,VIII,Estimación,900769.0,883661.0,903469.0,1026592.0,1104847.0,1120377.0,1081747.0
19,46,IX,Estimación,1249369.0,1245729.0,1252056.0,1470697.0,1459535.0,1546450.0,1599886.0
20,48,X,Estimación,2806064.0,2896140.0,2852938.0,3253812.0,3264100.0,3502355.0,3427933.0
21,50,Total,Estimación,785653.0,785854.0,798086.0,919432.0,947730.0,994216.0,916367.0
22,53,I,Estimación,37689.0,71481.0,65369.0,80570.0,84083.0,93255.0,110915.0
23,55,II,Estimación,19805.0,44384.0,39123.0,49518.0,52258.0,57905.0,108780.0
24,57,III,Estimación,16828.0,37490.0,31927.0,38390.0,42745.0,46001.0,87000.0
25,59,IV,Estimación,12474.0,30519.0,24759.0,30494.0,33103.0,38121.0,64187.0
26,61,V,Estimación,9724.0,23580.0,19018.0,24849.0,29019.0,29217.0,50741.0
27,63,VI,Estimación,7127.0,18756.0,15280.0,20559.0,21540.0,25266.0,39476.0
28,65,VII,Estimación,5636.0,14460.0,12373.0,14725.0,18004.0,18473.0,32267.0
29,67,VIII,Estimación,3431.0,11355.0,9766.0,10584.0,12645.0,15187.0,22378.0
30,69,IX,Estimación,2344.0,7218.0,5487.0,6546.0,8497.0,9724.0,11330.0
31,71,X,Estimación,772.0,2128.0,3739.0,4934.0,4821.0,5442.0,5403.0
32,73,Total,Estimación,11587.0,26196.0,22656.0,27981.0,30656.0,33789.0,53412.0
33,76,I,Estimación,138991.0,145669.0,161288.0,195235.0,203882.0,207111.0,124479.0
34,78,II,Estimación,266553.0,285498.0,300703.0,346835.0,372383.0,386743.0,306153.0
35,80,III,Estimación,350790.0,360429.0,378165.0,440471.0,470933.0,484261.0,430462.0
36,82,IV,Estimación,427467.0,452607.0,463986.0,518746.0,552571.0,572052.0,500747.0
37,84,V,Estimación,497262.0,499406.0,529955.0,605889.0,659830.0,668418.0,600590.0
38,86,VI,Estimación,591580.0,600425.0,607644.0,738608.0,765271.0,824982.0,741748.0
39,88,VII,Estimación,737367.0,734865.0,737540.0,846903.0,902091.0,930052.0,877522.0
40,90,VIII,Estimación,904200.0,895016.0,913235.0,1037176.0,1117492.0,1135564.0,1104125.0
41,92,IX,Estimación,1251713.0,1252947.0,1257543.0,1477243.0,1468032.0,1556174.0,1611216.0
42,94,X,Estimación,2806836.0,2898267.0,2856677.0,3258746.0,3268921.0,3507797.0,3433336.0
43,96,Total,Estimación,797240.0,812049.0,820742.0,947413.0,978386.0,1028005.0,969779.0

In [45]:
data_data = data_final.drop('nan', axis = 'columns')
data_data

,index,,2006,2009,2011,2013,2015,2017,2020
0,7,I,79949.0,55919.0,73469.0,79684.0,83200.0,78171.0,7024.0
1,9,II,204278.0,199662.0,208997.0,239032.0,256193.0,256276.0,114884.0
2,11,III,282025.0,268025.0,289738.0,322936.0,347779.0,349320.0,244414.0
3,13,IV,355635.0,359497.0,369361.0,406897.0,431396.0,444633.0,318832.0
4,15,V,408166.0,398138.0,427120.0,482404.0,532687.0,531117.0,418060.0
5,17,VI,494663.0,490126.0,491960.0,597094.0,627535.0,668494.0,554127.0
6,19,VII,633534.0,615680.0,613491.0,716311.0,748729.0,777771.0,668561.0
7,21,VIII,778701.0,748103.0,759060.0,871052.0,945771.0,957899.0,881290.0
8,23,IX,1082354.0,1042140.0,1054628.0,1271892.0,1228070.0,1315693.0,1349157.0
9,25,X,2473316.0,2511833.0,2503995.0,2877024.0,2821696.0,3052409.0,2942239.0
10,27,Total,679233.0,668447.0,679246.0,787292.0,802526.0,843821.0,746865.0
11,30,I,101302.0,74187.0,95919.0,114665.0,119799.0,113855.0,13564.0
12,32,II,246747.0,241114.0,261580.0,297317.0,320126.0,328838.0,197373.0
13,34,III,333961.0,322938.0,346238.0,402080.0,428188.0,438260.0,343462.0
14,36,IV,414994.0,422088.0,439227.0,488252.0,519468.0,533930.0,436560.0
15,38,V,487538.0,475826.0,510937.0,581040.0,630811.0,639201.0,549849.0
16,40,VI,584453.0,581669.0,592364.0,718050.0,743731.0,799716.0,702272.0
17,42,VII,731731.0,720406.0,725167.0,832178.0,884086.0,911580.0,845255.0
18,44,VIII,900769.0,883661.0,903469.0,1026592.0,1104847.0,1120377.0,1081747.0
19,46,IX,1249369.0,1245729.0,1252056.0,1470697.0,1459535.0,1546450.0,1599886.0
20,48,X,2806064.0,2896140.0,2852938.0,3253812.0,3264100.0,3502355.0,3427933.0
21,50,Total,785653.0,785854.0,798086.0,919432.0,947730.0,994216.0,916367.0
22,53,I,37689.0,71481.0,65369.0,80570.0,84083.0,93255.0,110915.0
23,55,II,19805.0,44384.0,39123.0,49518.0,52258.0,57905.0,108780.0
24,57,III,16828.0,37490.0,31927.0,38390.0,42745.0,46001.0,87000.0
25,59,IV,12474.0,30519.0,24759.0,30494.0,33103.0,38121.0,64187.0
26,61,V,9724.0,23580.0,19018.0,24849.0,29019.0,29217.0,50741.0
27,63,VI,7127.0,18756.0,15280.0,20559.0,21540.0,25266.0,39476.0
28,65,VII,5636.0,14460.0,12373.0,14725.0,18004.0,18473.0,32267.0
29,67,VIII,3431.0,11355.0,9766.0,10584.0,12645.0,15187.0,22378.0
30,69,IX,2344.0,7218.0,5487.0,6546.0,8497.0,9724.0,11330.0
31,71,X,772.0,2128.0,3739.0,4934.0,4821.0,5442.0,5403.0
32,73,Total,11587.0,26196.0,22656.0,27981.0,30656.0,33789.0,53412.0
33,76,I,138991.0,145669.0,161288.0,195235.0,203882.0,207111.0,124479.0
34,78,II,266553.0,285498.0,300703.0,346835.0,372383.0,386743.0,306153.0
35,80,III,350790.0,360429.0,378165.0,440471.0,470933.0,484261.0,430462.0
36,82,IV,427467.0,452607.0,463986.0,518746.0,552571.0,572052.0,500747.0
37,84,V,497262.0,499406.0,529955.0,605889.0,659830.0,668418.0,600590.0
38,86,VI,591580.0,600425.0,607644.0,738608.0,765271.0,824982.0,741748.0
39,88,VII,737367.0,734865.0,737540.0,846903.0,902091.0,930052.0,877522.0
40,90,VIII,904200.0,895016.0,913235.0,1037176.0,1117492.0,1135564.0,1104125.0
41,92,IX,1251713.0,1252947.0,1257543.0,1477243.0,1468032.0,1556174.0,1611216.0
42,94,X,2806836.0,2898267.0,2856677.0,3258746.0,3268921.0,3507797.0,3433336.0
43,96,Total,797240.0,812049.0,820742.0,947413.0,978386.0,1028005.0,969779.0

In [46]:
data_data = data_data.drop('index', axis = 'columns')
data_data

,,2006,2009,2011,2013,2015,2017,2020
0,I,79949.0,55919.0,73469.0,79684.0,83200.0,78171.0,7024.0
1,II,204278.0,199662.0,208997.0,239032.0,256193.0,256276.0,114884.0
2,III,282025.0,268025.0,289738.0,322936.0,347779.0,349320.0,244414.0
3,IV,355635.0,359497.0,369361.0,406897.0,431396.0,444633.0,318832.0
4,V,408166.0,398138.0,427120.0,482404.0,532687.0,531117.0,418060.0
5,VI,494663.0,490126.0,491960.0,597094.0,627535.0,668494.0,554127.0
6,VII,633534.0,615680.0,613491.0,716311.0,748729.0,777771.0,668561.0
7,VIII,778701.0,748103.0,759060.0,871052.0,945771.0,957899.0,881290.0
8,IX,1082354.0,1042140.0,1054628.0,1271892.0,1228070.0,1315693.0,1349157.0
9,X,2473316.0,2511833.0,2503995.0,2877024.0,2821696.0,3052409.0,2942239.0
10,Total,679233.0,668447.0,679246.0,787292.0,802526.0,843821.0,746865.0
11,I,101302.0,74187.0,95919.0,114665.0,119799.0,113855.0,13564.0
12,II,246747.0,241114.0,261580.0,297317.0,320126.0,328838.0,197373.0
13,III,333961.0,322938.0,346238.0,402080.0,428188.0,438260.0,343462.0
14,IV,414994.0,422088.0,439227.0,488252.0,519468.0,533930.0,436560.0
15,V,487538.0,475826.0,510937.0,581040.0,630811.0,639201.0,549849.0
16,VI,584453.0,581669.0,592364.0,718050.0,743731.0,799716.0,702272.0
17,VII,731731.0,720406.0,725167.0,832178.0,884086.0,911580.0,845255.0
18,VIII,900769.0,883661.0,903469.0,1026592.0,1104847.0,1120377.0,1081747.0
19,IX,1249369.0,1245729.0,1252056.0,1470697.0,1459535.0,1546450.0,1599886.0
20,X,2806064.0,2896140.0,2852938.0,3253812.0,3264100.0,3502355.0,3427933.0
21,Total,785653.0,785854.0,798086.0,919432.0,947730.0,994216.0,916367.0
22,I,37689.0,71481.0,65369.0,80570.0,84083.0,93255.0,110915.0
23,II,19805.0,44384.0,39123.0,49518.0,52258.0,57905.0,108780.0
24,III,16828.0,37490.0,31927.0,38390.0,42745.0,46001.0,87000.0
25,IV,12474.0,30519.0,24759.0,30494.0,33103.0,38121.0,64187.0
26,V,9724.0,23580.0,19018.0,24849.0,29019.0,29217.0,50741.0
27,VI,7127.0,18756.0,15280.0,20559.0,21540.0,25266.0,39476.0
28,VII,5636.0,14460.0,12373.0,14725.0,18004.0,18473.0,32267.0
29,VIII,3431.0,11355.0,9766.0,10584.0,12645.0,15187.0,22378.0
30,IX,2344.0,7218.0,5487.0,6546.0,8497.0,9724.0,11330.0
31,X,772.0,2128.0,3739.0,4934.0,4821.0,5442.0,5403.0
32,Total,11587.0,26196.0,22656.0,27981.0,30656.0,33789.0,53412.0
33,I,138991.0,145669.0,161288.0,195235.0,203882.0,207111.0,124479.0
34,II,266553.0,285498.0,300703.0,346835.0,372383.0,386743.0,306153.0
35,III,350790.0,360429.0,378165.0,440471.0,470933.0,484261.0,430462.0
36,IV,427467.0,452607.0,463986.0,518746.0,552571.0,572052.0,500747.0
37,V,497262.0,499406.0,529955.0,605889.0,659830.0,668418.0,600590.0
38,VI,591580.0,600425.0,607644.0,738608.0,765271.0,824982.0,741748.0
39,VII,737367.0,734865.0,737540.0,846903.0,902091.0,930052.0,877522.0
40,VIII,904200.0,895016.0,913235.0,1037176.0,1117492.0,1135564.0,1104125.0
41,IX,1251713.0,1252947.0,1257543.0,1477243.0,1468032.0,1556174.0,1611216.0
42,X,2806836.0,2898267.0,2856677.0,3258746.0,3268921.0,3507797.0,3433336.0
43,Total,797240.0,812049.0,820742.0,947413.0,978386.0,1028005.0,969779.0

In [47]:
data_data[33::]

,,2006,2009,2011,2013,2015,2017,2020
33,I,138991.0,145669.0,161288.0,195235.0,203882.0,207111.0,124479.0
34,II,266553.0,285498.0,300703.0,346835.0,372383.0,386743.0,306153.0
35,III,350790.0,360429.0,378165.0,440471.0,470933.0,484261.0,430462.0
36,IV,427467.0,452607.0,463986.0,518746.0,552571.0,572052.0,500747.0
37,V,497262.0,499406.0,529955.0,605889.0,659830.0,668418.0,600590.0
38,VI,591580.0,600425.0,607644.0,738608.0,765271.0,824982.0,741748.0
39,VII,737367.0,734865.0,737540.0,846903.0,902091.0,930052.0,877522.0
40,VIII,904200.0,895016.0,913235.0,1037176.0,1117492.0,1135564.0,1104125.0
41,IX,1251713.0,1252947.0,1257543.0,1477243.0,1468032.0,1556174.0,1611216.0
42,X,2806836.0,2898267.0,2856677.0,3258746.0,3268921.0,3507797.0,3433336.0
43,Total,797240.0,812049.0,820742.0,947413.0,978386.0,1028005.0,969779.0